/**
 * GERADO POR `ferramentas/gera-catalogo-simbolos.mjs` — NÃO EDITE À MÃO.
 *
 * Catálogo completo de símbolos do KaTeX 0.17.0,
 * 686 entradas, extraídas de `node_modules/katex/src` e conferidas uma a uma
 * pela própria renderização. É o teto real do editor: o que não está aqui o
 * KaTeX não desenha, e a prévia recusaria.
 *
 * As paletas curadas de `paletas.ts` vêm ANTES destas na tela — elas têm nome,
 * gabarito de cursor e ordem pensados à mão. Isto é a cauda longa.
 *
 * Campos: l = o que é inserido (`@` marca onde o cursor para) ·
 * n = nome em português · m = o que o botão desenha, quando difere de `l` ·
 * c = caractere (busca) · s = sinônimos que desenham o mesmo sinal (busca, não
 * aparecem na grade).
 */

export type ItemCatalogo = { l: string; n: string; m?: string; c?: string; s?: string }

export const CATALOGO: Record<string, ItemCatalogo[]> = {
  operacoes: [
    { l: "\\mp", n: "menos ou mais", c: "∓" },
    { l: "\\pm", n: "mais ou menos", c: "±", s: "\\plusmn" },
    { l: "\\wr", n: "produto entrelaçado", c: "≀" },
    { l: "\\And", n: "e comercial (espaçado)", c: "&" },
    { l: "\\ast", n: "asterisco", c: "∗" },
    { l: "\\cap", n: "interseção", c: "∩" },
    { l: "\\Cap", n: "interseção dupla", c: "⋒", s: "\\doublecap" },
    { l: "\\cup", n: "união", c: "∪" },
    { l: "\\Cup", n: "união dupla", c: "⋓", s: "\\doublecup" },
    { l: "\\div", n: "divisão", c: "÷" },
    { l: "\\int", n: "integral", c: "∫", s: "\\intop \\smallint" },
    { l: "\\lhd", n: "subgrupo normal à esquerda", c: "⊲" },
    { l: "\\lor", n: "ou lógico", c: "∨", s: "\\vee" },
    { l: "\\rhd", n: "subgrupo normal à direita", c: "⊳" },
    { l: "\\sum", n: "somatório", c: "∑" },
    { l: "\\cdot", n: "ponto de multiplicação", c: "⋅", s: "\\sdot" },
    { l: "\\circ", n: "composição", c: "∘" },
    { l: "\\iint", n: "integral dupla", c: "∬" },
    { l: "\\land", n: "e lógico", c: "∧", s: "\\wedge" },
    { l: "\\odot", n: "produto em círculo", c: "⊙" },
    { l: "\\oint", n: "integral de contorno", c: "∮" },
    { l: "\\prod", n: "produtório", c: "∏" },
    { l: "\\star", n: "estrela", c: "⋆" },
    { l: "\\amalg", n: "coproduto", c: "⨿" },
    { l: "\\iiint", n: "integral tripla", c: "∭" },
    { l: "\\oiint", n: "integral de superfície", c: "∯" },
    { l: "\\oplus", n: "soma direta", c: "⊕" },
    { l: "\\sqcap", n: "interseção (quadrado)", c: "⊓" },
    { l: "\\sqcup", n: "união (quadrado)", c: "⊔" },
    { l: "\\times", n: "multiplicação", c: "×" },
    { l: "\\unlhd", n: "subgrupo normal ou igual à esquerda", c: "⊴" },
    { l: "\\unrhd", n: "subgrupo normal ou igual à direita", c: "⊵" },
    { l: "\\uplus", n: "união com multiplicidade", c: "⊎" },
    { l: "\\bigcap", n: "interseção de vários", c: "⋂" },
    { l: "\\bigcup", n: "união de vários", c: "⋃" },
    { l: "\\bigvee", n: "ou lógico de vários", c: "⋁" },
    { l: "\\boxdot", n: "ponto em quadrado", c: "⊡" },
    { l: "\\bullet", n: "ponto cheio", c: "∙", s: "\\bull" },
    { l: "\\coprod", n: "coproduto de vários", c: "∐" },
    { l: "\\dagger", n: "adaga", c: "†" },
    { l: "\\gtrdot", n: "maior (ponto)", c: "⋗" },
    { l: "\\ltimes", n: "produto semidireto à esquerda", c: "⋉" },
    { l: "\\oiiint", n: "integral de volume", c: "∰" },
    { l: "\\ominus", n: "subtração em círculo", c: "⊖" },
    { l: "\\oslash", n: "divisão em círculo", c: "⊘" },
    { l: "\\otimes", n: "produto tensorial", c: "⊗" },
    { l: "\\rtimes", n: "produto semidireto à direita", c: "⋊" },
    { l: "\\veebar", n: "ou exclusivo", c: "⊻" },
    { l: "\\bigcirc", n: "círculo grande", c: "◯" },
    { l: "\\bigodot", n: "produto em círculo de vários", c: "⨀" },
    { l: "\\boxplus", n: "soma em quadrado", c: "⊞" },
    { l: "\\ddagger", n: "adaga dupla", c: "‡", s: "\\Dagger" },
    { l: "\\diamond", n: "losango pequeno", c: "⋄" },
    { l: "\\dotplus", n: "mais com ponto", c: "∔" },
    { l: "\\lessdot", n: "menor (ponto)", c: "⋖" },
    { l: "\\barwedge", n: "não-e", c: "⊼" },
    { l: "\\bigoplus", n: "soma direta de vários", c: "⨁" },
    { l: "\\bigsqcup", n: "união (quadrado) de vários", c: "⨆" },
    { l: "\\biguplus", n: "união com multiplicidade de vários", c: "⨄" },
    { l: "\\bigwedge", n: "e lógico de vários", c: "⋀" },
    { l: "\\boxminus", n: "subtração em quadrado", c: "⊟" },
    { l: "\\boxtimes", n: "produto em quadrado", c: "⊠" },
    { l: "\\curlyvee", n: "ou lógico curvo", c: "⋎" },
    { l: "\\intercal", n: "transposta", c: "⊺" },
    { l: "\\setminus", n: "diferença de conjuntos", c: "∖" },
    { l: "\\bigotimes", n: "produto tensorial de vários", c: "⨂" },
    { l: "\\centerdot", n: "centerdot", c: "⋅" },
    { l: "\\circledast", n: "asterisco em círculo", c: "⊛" },
    { l: "\\curlywedge", n: "e lógico curvo", c: "⋏" },
    { l: "\\circledcirc", n: "círculo em círculo", c: "⊚" },
    { l: "\\circleddash", n: "traço em círculo", c: "⊝" },
    { l: "\\triangleleft", n: "triângulo à esquerda", c: "◃" },
    { l: "\\bigtriangleup", n: "triângulo grande", c: "△" },
    { l: "\\divideontimes", n: "divisão vezes", c: "⋇" },
    { l: "\\smallsetminus", n: "diferença de conjuntos (menor)", c: "∖" },
    { l: "\\triangleright", n: "triângulo à direita", c: "▹" },
    { l: "\\doublebarwedge", n: "e lógico com duas barras", c: "⩞" },
    { l: "\\leftthreetimes", n: "produto semidireto à esquerda (três)", c: "⋋" },
    { l: "\\bigtriangledown", n: "triângulo grande invertido", c: "▽" },
    { l: "\\rightthreetimes", n: "produto semidireto à direita (três)", c: "⋌" },
    { l: "\\ratio", n: "razão (dois pontos)", c: ":", s: "\\vcentcolon" },
    { l: "\\minuso", n: "menos em círculo", c: "⦵" },
    { l: "\\coloneq", n: "define como (:−)", s: "\\colonminus" },
    { l: "\\Coloneq", n: "define como (::−)", s: "\\coloncolonminus" },
    { l: "\\eqcolon", n: "é definido por (−:)", c: "∹", s: "\\minuscolon" },
    { l: "\\Eqcolon", n: "é definido por (−::)", s: "\\minuscoloncolon" },
    { l: "\\coloneqq", n: "define como (:=)", c: "≔", s: "\\colonequals" },
    { l: "\\Coloneqq", n: "define como (::=)", s: "\\coloncolonequals" },
    { l: "\\colonsim", n: "define como semelhante" },
    { l: "\\Colonsim", n: "define como semelhante (duplo)", s: "\\coloncolonsim" },
    { l: "\\dblcolon", n: "dois pontos duplos", c: "∷", s: "\\coloncolon" },
    { l: "\\colonapprox", n: "define como aproximado" },
    { l: "\\Colonapprox", n: "define como aproximado (duplo)", s: "\\coloncolonapprox" },
  ],
  grego: [
    { l: "\\mu", n: "mi", c: "μ" },
    { l: "\\nu", n: "ni", c: "ν" },
    { l: "\\pi", n: "pi", c: "π" },
    { l: "\\Pi", n: "Pi maiúsculo", c: "Π" },
    { l: "\\xi", n: "csi", c: "ξ" },
    { l: "\\Xi", n: "Csi maiúsculo", c: "Ξ" },
    { l: "\\chi", n: "qui", c: "χ" },
    { l: "\\eta", n: "eta", c: "η" },
    { l: "\\phi", n: "fi", c: "ϕ" },
    { l: "\\Phi", n: "Fi maiúsculo", c: "Φ" },
    { l: "\\psi", n: "psi", c: "ψ" },
    { l: "\\Psi", n: "Psi maiúsculo", c: "Ψ" },
    { l: "\\rho", n: "rô", c: "ρ" },
    { l: "\\tau", n: "tau", c: "τ" },
    { l: "\\beta", n: "beta", c: "β" },
    { l: "\\beth", n: "bete", c: "ℶ" },
    { l: "\\iota", n: "iota", c: "ι" },
    { l: "\\zeta", n: "zeta", c: "ζ" },
    { l: "\\aleph", n: "álefe", c: "ℵ", s: "\\alef \\alefsym" },
    { l: "\\alpha", n: "alfa", c: "α" },
    { l: "\\delta", n: "delta", c: "δ" },
    { l: "\\Delta", n: "Delta maiúsculo (variação)", c: "Δ" },
    { l: "\\gamma", n: "gama", c: "γ" },
    { l: "\\Gamma", n: "Gama maiúsculo", c: "Γ" },
    { l: "\\gimel", n: "guímel", c: "ℷ" },
    { l: "\\kappa", n: "capa", c: "κ" },
    { l: "\\omega", n: "ômega", c: "ω" },
    { l: "\\Omega", n: "Ômega maiúsculo", c: "Ω" },
    { l: "\\sigma", n: "sigma", c: "σ" },
    { l: "\\Sigma", n: "Sigma maiúsculo", c: "Σ" },
    { l: "\\theta", n: "teta", c: "θ" },
    { l: "\\Theta", n: "Teta maiúsculo", c: "Θ" },
    { l: "\\varpi", n: "pi variante", c: "ϖ" },
    { l: "\\daleth", n: "dálete", c: "ℸ" },
    { l: "\\lambda", n: "lambda", c: "λ" },
    { l: "\\Lambda", n: "Lambda maiúsculo", c: "Λ" },
    { l: "\\varphi", n: "fi variante", c: "φ" },
    { l: "\\varrho", n: "rô variante", c: "ϱ" },
    { l: "\\digamma", n: "digama", c: "ϝ" },
    { l: "\\epsilon", n: "épsilon", c: "ϵ" },
    { l: "\\omicron", n: "ômicron", c: "ο" },
    { l: "\\upsilon", n: "úpsilon", c: "υ" },
    { l: "\\Upsilon", n: "Úpsilon maiúsculo", c: "Υ" },
    { l: "\\varkappa", n: "capa variante", c: "ϰ" },
    { l: "\\varsigma", n: "sigma final", c: "ς" },
    { l: "\\vartheta", n: "teta variante", c: "ϑ", s: "\\thetasym" },
    { l: "\\varepsilon", n: "épsilon variante", c: "ε" },
    { l: "\\Mu", n: "Mi maiúsculo", c: "M" },
    { l: "\\Nu", n: "Ni maiúsculo", c: "N" },
    { l: "\\Eta", n: "Eta maiúsculo", c: "H" },
    { l: "\\Rho", n: "Rô maiúsculo", c: "P" },
    { l: "\\Tau", n: "Tau maiúsculo", c: "T" },
    { l: "\\Bbbk", n: "k vazado", c: "k" },
    { l: "\\Beta", n: "Beta maiúsculo", c: "B" },
    { l: "\\Iota", n: "Iota maiúsculo", c: "I" },
    { l: "\\Zeta", n: "Zeta maiúsculo", c: "Z" },
    { l: "\\Alpha", n: "Alfa maiúsculo", c: "A" },
    { l: "\\Kappa", n: "Capa maiúsculo", c: "K" },
    { l: "\\varPi", n: "Pi maiúsculo em itálico", c: "Π" },
    { l: "\\varXi", n: "Csi maiúsculo em itálico", c: "Ξ" },
    { l: "\\varPhi", n: "Fi maiúsculo em itálico", c: "Φ" },
    { l: "\\varPsi", n: "Psi maiúsculo em itálico", c: "Ψ" },
    { l: "\\Epsilon", n: "Épsilon maiúsculo", c: "E" },
    { l: "\\Omicron", n: "Ômicron maiúsculo", c: "O" },
    { l: "\\varDelta", n: "Delta maiúsculo em itálico", c: "Δ" },
    { l: "\\varGamma", n: "Gama maiúsculo em itálico", c: "Γ" },
    { l: "\\varOmega", n: "Ômega maiúsculo em itálico", c: "Ω" },
    { l: "\\varSigma", n: "Sigma maiúsculo em itálico", c: "Σ" },
    { l: "\\varTheta", n: "Teta maiúsculo em itálico", c: "Θ" },
    { l: "\\varLambda", n: "Lambda maiúsculo em itálico", c: "Λ" },
    { l: "\\varUpsilon", n: "Úpsilon maiúsculo em itálico", c: "Υ" },
  ],
  relacoes: [
    { l: "\\ge", n: "maior ou igual", c: "≥", s: "\\geq" },
    { l: "\\gg", n: "muito maior", c: "≫" },
    { l: "\\in", n: "pertence", c: "∈", s: "\\isin" },
    { l: "\\le", n: "menor ou igual", c: "≤", s: "\\leq" },
    { l: "\\ll", n: "muito menor", c: "≪" },
    { l: "\\ni", n: "contém elemento", c: "∋", s: "\\owns" },
    { l: "\\ggg", n: "muitíssimo maior", c: "⋙", s: "\\gggtr" },
    { l: "\\lll", n: "muitíssimo menor", c: "⋘", s: "\\llless" },
    { l: "\\mid", n: "divide", c: "∣" },
    { l: "\\sim", n: "semelhante", c: "∼" },
    { l: "\\cong", n: "congruente", c: "≅" },
    { l: "\\geqq", n: "maior ou igual (duplo)", c: "≧" },
    { l: "\\gneq", n: "maior e diferente", c: "⪈" },
    { l: "\\Join", n: "junção", c: "⋈", s: "\\bowtie" },
    { l: "\\leqq", n: "menor ou igual (duplo)", c: "≦" },
    { l: "\\lneq", n: "menor e diferente", c: "⪇" },
    { l: "\\ngeq", n: "não maior ou igual", c: "≱" },
    { l: "\\ngtr", n: "não maior", c: "≯" },
    { l: "\\nleq", n: "não menor ou igual", c: "≰" },
    { l: "\\nmid", n: "não divide", c: "∤" },
    { l: "\\nsim", n: "não semelhante", c: "≁" },
    { l: "\\perp", n: "perpendicular", c: "⊥" },
    { l: "\\prec", n: "precede", c: "≺" },
    { l: "\\succ", n: "sucede", c: "≻" },
    { l: "\\asymp", n: "assintótico", c: "≍" },
    { l: "\\dashv", n: "é deduzido de", c: "⊣" },
    { l: "\\doteq", n: "define como igual", c: "≐" },
    { l: "\\Doteq", n: "igual por definição (duplo)", c: "≑", s: "\\doteqdot" },
    { l: "\\eqsim", n: "igual ou semelhante", c: "≂" },
    { l: "\\equiv", n: "equivalente", c: "≡" },
    { l: "\\frown", n: "carranca", c: "⌢" },
    { l: "\\gneqq", n: "maior e diferente (duplo)", c: "≩" },
    { l: "\\gnsim", n: "maior e não semelhante", c: "⋧" },
    { l: "\\lneqq", n: "menor e diferente (duplo)", c: "≨" },
    { l: "\\lnsim", n: "menor e não semelhante", c: "⋦" },
    { l: "\\ncong", n: "não congruente", c: "≆" },
    { l: "\\nless", n: "não menor", c: "≮" },
    { l: "\\nprec", n: "não precede", c: "⊀" },
    { l: "\\nsucc", n: "não sucede", c: "⊁" },
    { l: "\\simeq", n: "assintoticamente igual", c: "≃" },
    { l: "\\smile", n: "sorriso", c: "⌣" },
    { l: "\\vdash", n: "deduz", c: "⊢" },
    { l: "\\vDash", n: "satisfaz (duplo)", c: "⊨" },
    { l: "\\Vdash", n: "força (duplo)", c: "⊩" },
    { l: "\\approx", n: "aproximadamente", c: "≈" },
    { l: "\\bumpeq", n: "igual com arco", c: "≏" },
    { l: "\\Bumpeq", n: "igual com arco (duplo)", c: "≎" },
    { l: "\\circeq", n: "igual com círculo", c: "≗" },
    { l: "\\eqcirc", n: "círculo com igual", c: "≖" },
    { l: "\\gtrsim", n: "maior ou aproximado", c: "≳" },
    { l: "\\models", n: "satisfaz", c: "⊨" },
    { l: "\\nvdash", n: "não deduz", c: "⊬" },
    { l: "\\nvDash", n: "não satisfaz (duplo)", c: "⊭" },
    { l: "\\nVdash", n: "não força (duplo)", c: "⊮" },
    { l: "\\nVDash", n: "não satisfaz (duplo)", c: "⊯" },
    { l: "\\origof", n: "origem de", c: "⊶" },
    { l: "\\preceq", n: "precede ou igual", c: "⪯" },
    { l: "\\propto", n: "proporcional a", c: "∝" },
    { l: "\\subset", n: "contido", c: "⊂", s: "\\sub" },
    { l: "\\Subset", n: "contido (duplo)", c: "⋐" },
    { l: "\\succeq", n: "sucede ou igual", c: "⪰" },
    { l: "\\supset", n: "contém", c: "⊃" },
    { l: "\\Supset", n: "contém (duplo)", c: "⋑" },
    { l: "\\Vvdash", n: "força (triplo)", c: "⊪" },
    { l: "\\backsim", n: "semelhante (invertido)", c: "∽" },
    { l: "\\because", n: "porque", c: "∵" },
    { l: "\\between", n: "entre", c: "≬" },
    { l: "\\gtrless", n: "maior ou menor", c: "≷" },
    { l: "\\imageof", n: "imagem de", c: "⊷" },
    { l: "\\lessgtr", n: "menor ou maior", c: "≶" },
    { l: "\\lesssim", n: "menor ou aproximado", c: "≲" },
    { l: "\\npreceq", n: "não precede ou igual", c: "⋠" },
    { l: "\\nsucceq", n: "não sucede ou igual", c: "⋡" },
    { l: "\\precsim", n: "precede ou semelhante", c: "≾" },
    { l: "\\succsim", n: "sucede ou semelhante", c: "≿" },
    { l: "\\approxeq", n: "aproximadamente igual", c: "≊" },
    { l: "\\geqslant", n: "maior ou igual (inclinado)", c: "⩾" },
    { l: "\\gnapprox", n: "maior e não aproximado", c: "⪊" },
    { l: "\\leqslant", n: "menor ou igual (inclinado)", c: "⩽" },
    { l: "\\lnapprox", n: "menor e não aproximado", c: "⪉" },
    { l: "\\parallel", n: "paralelo", c: "∥" },
    { l: "\\precneqq", n: "precede e diferente", c: "⪵" },
    { l: "\\precnsim", n: "precede e não semelhante", c: "⋨" },
    { l: "\\shortmid", n: "shortmid", c: "∣" },
    { l: "\\sqsubset", n: "contido próprio (quadrado)", c: "⊏" },
    { l: "\\sqsupset", n: "contém próprio (quadrado)", c: "⊐" },
    { l: "\\subseteq", n: "contido ou igual", c: "⊆", s: "\\sube" },
    { l: "\\succneqq", n: "sucede e diferente", c: "⪶" },
    { l: "\\succnsim", n: "sucede e não semelhante", c: "⋩" },
    { l: "\\supseteq", n: "contém ou igual", c: "⊇", s: "\\supe" },
    { l: "\\thicksim", n: "thicksim", c: "∼" },
    { l: "\\backsimeq", n: "assintoticamente igual (invertido)", c: "⋍" },
    { l: "\\gtrapprox", n: "maior ou aproximadamente igual", c: "⪆" },
    { l: "\\gtreqless", n: "maior, igual ou menor", c: "⋛" },
    { l: "\\lesseqgtr", n: "menor, igual ou maior", c: "⋚" },
    { l: "\\nparallel", n: "não paralelo", c: "∦" },
    { l: "\\nsubseteq", n: "não contido", c: "⊈" },
    { l: "\\nsupseteq", n: "não contém", c: "⊉" },
    { l: "\\pitchfork", n: "forquilha", c: "⋔" },
    { l: "\\subseteqq", n: "contido ou igual (duplo)", c: "⫅" },
    { l: "\\subsetneq", n: "contido estritamente", c: "⊊" },
    { l: "\\supseteqq", n: "contém ou igual (duplo)", c: "⫆" },
    { l: "\\supsetneq", n: "contém estritamente", c: "⊋" },
    { l: "\\therefore", n: "portanto", c: "∴" },
    { l: "\\triangleq", n: "igual por definição", c: "≜" },
    { l: "\\varpropto", n: "proporcional a (variante)", c: "∝" },
    { l: "\\eqslantgtr", n: "maior ou igual (inclinado, AMS)", c: "⪖" },
    { l: "\\gtreqqless", n: "maior, igual ou menor (duplo)", c: "⪌" },
    { l: "\\lessapprox", n: "menor ou aproximadamente igual", c: "⪅" },
    { l: "\\lesseqqgtr", n: "menor, igual ou maior (duplo)", c: "⪋" },
    { l: "\\precapprox", n: "precede ou aproximado", c: "⪷" },
    { l: "\\smallfrown", n: "smallfrown", c: "⌢" },
    { l: "\\smallsmile", n: "smallsmile", c: "⌣" },
    { l: "\\sqsubseteq", n: "contido (quadrado)", c: "⊑" },
    { l: "\\sqsupseteq", n: "contém (quadrado)", c: "⊒" },
    { l: "\\subsetneqq", n: "contido estritamente (duplo)", c: "⫋" },
    { l: "\\succapprox", n: "sucede ou aproximado", c: "⪸" },
    { l: "\\supsetneqq", n: "contém estritamente (duplo)", c: "⫌" },
    { l: "\\backepsilon", n: "épsilon invertido (tal que)", c: "∍" },
    { l: "\\curlyeqprec", n: "igual curvo que precede", c: "⋞" },
    { l: "\\curlyeqsucc", n: "igual curvo que sucede", c: "⋟" },
    { l: "\\eqslantless", n: "menor ou igual (inclinado, AMS)", c: "⪕" },
    { l: "\\preccurlyeq", n: "precede ou igual (curvo)", c: "≼" },
    { l: "\\precnapprox", n: "precede e não aproximado", c: "⪹" },
    { l: "\\succcurlyeq", n: "sucede ou igual (curvo)", c: "≽" },
    { l: "\\succnapprox", n: "sucede e não aproximado", c: "⪺" },
    { l: "\\thickapprox", n: "thickapprox", c: "≈" },
    { l: "\\vartriangle", n: "triângulo (relação)", c: "△" },
    { l: "\\risingdotseq", n: "igual com pontos subindo", c: "≓" },
    { l: "\\fallingdotseq", n: "igual com pontos descendo", c: "≒" },
    { l: "\\ntriangleleft", n: "não triângulo à esquerda", c: "⋪" },
    { l: "\\shortparallel", n: "shortparallel", c: "∥" },
    { l: "\\ntriangleright", n: "não triângulo à direita", c: "⋫" },
    { l: "\\trianglelefteq", n: "subgrupo normal ou igual à esquerda", c: "⊴" },
    { l: "\\ntrianglelefteq", n: "não subgrupo normal ou igual à esquerda", c: "⋬" },
    { l: "\\trianglerighteq", n: "subgrupo normal ou igual à direita", c: "⊵" },
    { l: "\\vartriangleleft", n: "subgrupo normal à esquerda", c: "⊲" },
    { l: "\\ntrianglerighteq", n: "não subgrupo normal ou igual à direita", c: "⋭" },
    { l: "\\vartriangleright", n: "subgrupo normal à direita", c: "⊳" },
    { l: "\\blacktriangleleft", n: "triângulo cheio à esquerda", c: "◀" },
    { l: "\\blacktriangleright", n: "triângulo cheio à direita", c: "▶" },
    { l: "\\ne", n: "diferente", c: "≠", s: "\\neq" },
    { l: "\\not", n: "barra de negação (sobre o próximo)", c: "̸" },
    { l: "\\darr", n: "seta para baixo", c: "↓" },
    { l: "\\dArr", n: "seta dupla para baixo", c: "⇓", s: "\\Darr" },
    { l: "\\harr", n: "seta para os dois lados", c: "↔", s: "\\lrarr" },
    { l: "\\hArr", n: "seta dupla para os dois lados", c: "⇔", s: "\\Harr \\lrArr \\Lrarr" },
    { l: "\\larr", n: "seta para a esquerda", c: "←" },
    { l: "\\lArr", n: "seta dupla para a esquerda", c: "⇐", s: "\\Larr" },
    { l: "\\rarr", n: "seta para a direita", c: "→" },
    { l: "\\rArr", n: "seta dupla para a direita", c: "⇒", s: "\\Rarr" },
    { l: "\\uarr", n: "seta para cima", c: "↑" },
    { l: "\\uArr", n: "seta dupla para cima", c: "⇑", s: "\\Uarr" },
    { l: "\\colon", n: "dois pontos" },
    { l: "\\ngeqq", n: "não maior ou igual (duplo)", c: "≱" },
    { l: "\\nleqq", n: "não menor ou igual (duplo)", c: "≰" },
    { l: "\\notin", n: "não pertence", c: "∉" },
    { l: "\\notni", n: "não contém elemento", c: "∌" },
    { l: "\\eqqcolon", n: "é definido por (=:)", c: "≕", s: "\\equalscolon" },
    { l: "\\Eqqcolon", n: "é definido por (=::)", s: "\\equalscoloncolon" },
    { l: "\\simcolon", n: "semelhante por definição" },
    { l: "\\gvertneqq", n: "maior e diferente (barra)", c: "≩" },
    { l: "\\lvertneqq", n: "menor e diferente (barra)", c: "≨" },
    { l: "\\ngeqslant", n: "não maior ou igual (inclinado)", c: "≱" },
    { l: "\\nleqslant", n: "não menor ou igual (inclinado)", c: "≰" },
    { l: "\\nshortmid", n: "não divide (curto)", c: "∤" },
    { l: "\\nsubseteqq", n: "não contido ou igual (duplo)", c: "⊈" },
    { l: "\\nsupseteqq", n: "não contém ou igual (duplo)", c: "⊉" },
    { l: "\\approxcolon", n: "aproximado por definição" },
    { l: "\\varsubsetneq", n: "contido estritamente (variante)", c: "⊊" },
    { l: "\\varsupsetneq", n: "contém estritamente (variante)", c: "⊋" },
    { l: "\\ordinarycolon", n: "dois pontos comuns", c: ":" },
    { l: "\\simcoloncolon", n: "semelhante por definição (duplo)" },
    { l: "\\varsubsetneqq", n: "contido estritamente (duplo, variante)", c: "⫋" },
    { l: "\\varsupsetneqq", n: "contém estritamente (duplo, variante)", c: "⫌" },
    { l: "\\nshortparallel", n: "não paralelo (curto)", c: "∦" },
    { l: "\\approxcoloncolon", n: "aproximado por definição (duplo)" },
  ],
  setas: [
    { l: "\\to", n: "seta para a direita", c: "→", s: "\\rightarrow" },
    { l: "\\Lsh", n: "sobe e vira à esquerda", c: "↰" },
    { l: "\\Rsh", n: "sobe e vira à direita", c: "↱" },
    { l: "\\gets", n: "seta para a esquerda", c: "←", s: "\\leftarrow" },
    { l: "\\mapsto", n: "leva a", c: "↦" },
    { l: "\\leadsto", n: "leva a (ondulada)", c: "⇝", s: "\\rightsquigarrow" },
    { l: "\\nearrow", n: "seta nordeste", c: "↗" },
    { l: "\\nwarrow", n: "seta noroeste", c: "↖" },
    { l: "\\searrow", n: "seta sudeste", c: "↘" },
    { l: "\\swarrow", n: "seta sudoeste", c: "↙" },
    { l: "\\uparrow", n: "seta para cima", c: "↑" },
    { l: "\\Uparrow", n: "seta dupla para cima", c: "⇑" },
    { l: "\\multimap", n: "multimapa", c: "⊸" },
    { l: "\\downarrow", n: "seta para baixo", c: "↓" },
    { l: "\\Downarrow", n: "seta dupla para baixo", c: "⇓" },
    { l: "\\Leftarrow", n: "é implicado por", c: "⇐" },
    { l: "\\Lleftarrow", n: "seta para a esquerda dupla", c: "⇚" },
    { l: "\\longmapsto", n: "leva a (longa)", c: "⟼" },
    { l: "\\nleftarrow", n: "não seta para a esquerda", c: "↚" },
    { l: "\\nLeftarrow", n: "não é implicado por", c: "⇍" },
    { l: "\\Rightarrow", n: "implica", c: "⇒" },
    { l: "\\upuparrows", n: "duas setas para cima", c: "⇈" },
    { l: "\\nrightarrow", n: "não seta para a direita", c: "↛" },
    { l: "\\nRightarrow", n: "não implica", c: "⇏" },
    { l: "\\restriction", n: "restrição", c: "↾", s: "\\upharpoonright" },
    { l: "\\Rrightarrow", n: "seta para a direita dupla", c: "⇛" },
    { l: "\\updownarrow", n: "seta para cima e para baixo", c: "↕" },
    { l: "\\Updownarrow", n: "seta dupla para cima e para baixo", c: "⇕" },
    { l: "\\dashleftarrow", n: "seta para a esquerda, tracejada", c: "⇠" },
    { l: "\\hookleftarrow", n: "seta para a esquerda, com gancho", c: "↩" },
    { l: "\\leftarrowtail", n: "seta à esquerda com cauda", c: "↢" },
    { l: "\\leftharpoonup", n: "arpão à esquerda, gume em cima", c: "↼" },
    { l: "\\longleftarrow", n: "seta para a esquerda, longa", c: "⟵" },
    { l: "\\Longleftarrow", n: "seta para a esquerda dupla, longa", c: "⟸" },
    { l: "\\looparrowleft", n: "seta à esquerda com laço", c: "↫" },
    { l: "\\upharpoonleft", n: "arpão para cima, gume à esquerda", c: "↿" },
    { l: "\\curvearrowleft", n: "seta curva à esquerda", c: "↶" },
    { l: "\\dashrightarrow", n: "seta para a direita, tracejada", c: "⇢" },
    { l: "\\downdownarrows", n: "duas setas para baixo", c: "⇊" },
    { l: "\\hookrightarrow", n: "seta para a direita, com gancho", c: "↪" },
    { l: "\\leftleftarrows", n: "setas para a esquerda", c: "⇇" },
    { l: "\\leftrightarrow", n: "seta para os dois lados", c: "↔" },
    { l: "\\Leftrightarrow", n: "se e somente se", c: "⇔" },
    { l: "\\longrightarrow", n: "seta para a direita, longa", c: "⟶" },
    { l: "\\Longrightarrow", n: "seta para a direita dupla, longa", c: "⟹" },
    { l: "\\looparrowright", n: "seta à direita com laço", c: "↬" },
    { l: "\\rightarrowtail", n: "seta à direita com cauda", c: "↣" },
    { l: "\\rightharpoonup", n: "arpão à direita, gume em cima", c: "⇀" },
    { l: "\\circlearrowleft", n: "seta circular anti-horária", c: "↺" },
    { l: "\\curvearrowright", n: "seta curva à direita", c: "↷" },
    { l: "\\downharpoonleft", n: "arpão para baixo, gume à esquerda", c: "⇃" },
    { l: "\\leftharpoondown", n: "arpão à esquerda, gume embaixo", c: "↽" },
    { l: "\\leftrightarrows", n: "setas para os dois lados (paralelas)", c: "⇆" },
    { l: "\\nleftrightarrow", n: "não seta para os dois lados", c: "↮" },
    { l: "\\nLeftrightarrow", n: "não se e somente se", c: "⇎" },
    { l: "\\rightleftarrows", n: "setas para a esquerda", c: "⇄" },
    { l: "\\circlearrowright", n: "seta circular horária", c: "↻" },
    { l: "\\downharpoonright", n: "arpão para baixo, gume à direita", c: "⇂" },
    { l: "\\rightharpoondown", n: "arpão à direita, gume embaixo", c: "⇁" },
    { l: "\\rightrightarrows", n: "setas para a direita", c: "⇉" },
    { l: "\\twoheadleftarrow", n: "seta para a esquerda, de duas pontas, de duas pontas", c: "↞" },
    { l: "\\leftrightharpoons", n: "arpões para os dois lados", c: "⇋" },
    { l: "\\rightleftharpoons", n: "equilíbrio (setas opostas)", c: "⇌" },
    { l: "\\twoheadrightarrow", n: "seta para a direita, de duas pontas, de duas pontas", c: "↠" },
    { l: "\\longleftrightarrow", n: "seta para os dois lados, longa", c: "⟷" },
    { l: "\\Longleftrightarrow", n: "seta para os dois lados dupla, longa", c: "⟺" },
    { l: "\\leftrightsquigarrow", n: "seta ondulada para os dois lados", c: "↭" },
    { l: "\\iff", n: "se e somente se (com espaço)", c: "⟺" },
    { l: "\\implies", n: "implica (com espaço)", c: "⟹" },
    { l: "\\impliedby", n: "é implicado por (com espaço)", c: "⟸" },
  ],
  simbolos: [
    { l: "\\P", n: "pilcrow", c: "¶" },
    { l: "\\S", n: "parágrafo (seção)", c: "§", s: "\\sect" },
    { l: "\\Im", n: "parte imaginária", c: "ℑ", s: "\\image" },
    { l: "\\Re", n: "parte real", c: "ℜ", s: "\\real" },
    { l: "\\wp", n: "p de Weierstrass", c: "℘", s: "\\weierp" },
    { l: "\\bot", n: "falso", c: "⊥" },
    { l: "\\Box", n: "quadrado vazio", c: "□", s: "\\square" },
    { l: "\\dag", n: "adaga", c: "†" },
    { l: "\\ell", n: "ele cursivo", c: "ℓ" },
    { l: "\\eth", n: "eth", c: "ð" },
    { l: "\\mho", n: "condutância (mho)", c: "℧" },
    { l: "\\neg", n: "negação", c: "¬", s: "\\lnot" },
    { l: "\\top", n: "verdadeiro", c: "⊤" },
    { l: "\\yen", n: "iene", c: "¥" },
    { l: "\\ddag", n: "adaga dupla", c: "‡" },
    { l: "\\Finv", n: "F invertido", c: "Ⅎ" },
    { l: "\\flat", n: "bemol", c: "♭" },
    { l: "\\Game", n: "G invertido", c: "⅁" },
    { l: "\\hbar", n: "h cortado (Planck reduzida)", c: "ℏ" },
    { l: "\\surd", n: "radical", c: "√" },
    { l: "\\angle", n: "ângulo", c: "∠" },
    { l: "\\cdotp", n: "ponto centrado", c: "⋅" },
    { l: "\\ddots", n: "reticências diagonais", c: "⋱" },
    { l: "\\infty", n: "infinito", c: "∞", s: "\\infin" },
    { l: "\\ldotp", n: "ponto na base", c: "." },
    { l: "\\ldots", n: "reticências na base", c: "…", s: "\\mathellipsis \\dots \\dotsc \\dotso" },
    { l: "\\nabla", n: "nabla (gradiente)", c: "∇" },
    { l: "\\prime", n: "linha (derivada)", c: "′" },
    { l: "\\sharp", n: "sustenido", c: "♯" },
    { l: "\\degree", n: "grau", c: "°" },
    { l: "\\diagup", n: "barra diagonal", c: "╱" },
    { l: "\\exists", n: "existe", c: "∃", s: "\\exist" },
    { l: "\\forall", n: "para todo", c: "∀" },
    { l: "\\hslash", n: "h cortado (variante)", c: "ℏ" },
    { l: "\\pounds", n: "libra", c: "£", s: "\\mathsterling" },
    { l: "\\bigstar", n: "estrela cheia", c: "★" },
    { l: "\\Diamond", n: "losango vazio", c: "◊", s: "\\lozenge" },
    { l: "\\maltese", n: "cruz de malta", c: "✠" },
    { l: "\\natural", n: "bequadro", c: "♮" },
    { l: "\\nexists", n: "não existe", c: "∄" },
    { l: "\\nobreak", n: "não quebrar aqui" },
    { l: "\\partial", n: "derivada parcial", c: "∂" },
    { l: "\\circledR", n: "marca registrada", c: "®" },
    { l: "\\circledS", n: "S em círculo", c: "Ⓢ" },
    { l: "\\clubsuit", n: "paus", c: "♣", s: "\\clubs" },
    { l: "\\diagdown", n: "barra diagonal invertida", c: "╲" },
    { l: "\\emptyset", n: "conjunto vazio", c: "∅", s: "\\empty" },
    { l: "\\triangle", n: "triângulo", c: "△" },
    { l: "\\varvdots", n: "reticências verticais", c: "⋮" },
    { l: "\\backprime", n: "linha invertida", c: "‵" },
    { l: "\\checkmark", n: "visto", c: "✓" },
    { l: "\\heartsuit", n: "copas", c: "♡", s: "\\hearts" },
    { l: "\\spadesuit", n: "espadas", c: "♠", s: "\\spades" },
    { l: "\\allowbreak", n: "pode quebrar aqui" },
    { l: "\\complement", n: "complementar", c: "∁" },
    { l: "\\varnothing", n: "conjunto vazio (variante)", c: "∅" },
    { l: "\\blacksquare", n: "quadrado cheio", c: "■" },
    { l: "\\diamondsuit", n: "ouros", c: "♢", s: "\\diamonds" },
    { l: "\\blacklozenge", n: "losango cheio", c: "⧫" },
    { l: "\\triangledown", n: "triângulo invertido", c: "▽" },
    { l: "\\blacktriangle", n: "triângulo cheio", c: "▲" },
    { l: "\\measuredangle", n: "ângulo medido", c: "∡" },
    { l: "\\sphericalangle", n: "ângulo esférico", c: "∢" },
    { l: "\\blacktriangledown", n: "triângulo cheio invertido", c: "▼" },
    { l: "\\N", n: "números naturais", c: "N", s: "\\natnums" },
    { l: "\\R", n: "números reais", c: "R", s: "\\reals \\Reals" },
    { l: "\\Z", n: "números inteiros", c: "Z" },
    { l: "\\aa", n: "a com anel" },
    { l: "\\AA", n: "A com anel" },
    { l: "\\lq", n: "aspa simples esquerda", c: "‘" },
    { l: "\\rq", n: "aspa simples direita", c: "′" },
    { l: "\\Chi", n: "Qui maiúsculo", c: "X" },
    { l: "\\angln", n: "ângulo com n", c: "n" },
    { l: "\\cdots", n: "reticências centradas", c: "⋯", s: "\\dotsb \\dotsm" },
    { l: "\\cnums", n: "números complexos", c: "C", s: "\\Complex" },
    { l: "\\dotsi", n: "reticências entre integrais" },
    { l: "\\dotsx", n: "reticências (genérico)", c: "…" },
    { l: "\\imath", n: "i sem pingo", c: "ı" },
    { l: "\\jmath", n: "j sem pingo", c: "ȷ" },
    { l: "\\vdots", n: "reticências verticais", c: "⋮" },
    { l: "\\copyright", n: "direito autoral", c: "©" },
    { l: "\\textcopyright", n: "direito autoral", c: "©" },
    { l: "\\textregistered", n: "marca registrada", c: "®" },
  ],
  delimitadores: [
    { l: "\\gt", n: "maior", c: ">" },
    { l: "\\lt", n: "menor", c: "<" },
    { l: "\\vert", n: "barra vertical", c: "∣" },
    { l: "\\Vert", n: "barra vertical dupla", c: "∥" },
    { l: "\\lceil", n: "teto esquerdo", c: "⌈" },
    { l: "\\lvert", n: "módulo (abre)", c: "∣" },
    { l: "\\lVert", n: "norma (abre)", c: "∥" },
    { l: "\\rceil", n: "teto direito", c: "⌉" },
    { l: "\\rvert", n: "módulo (fecha)", c: "∣" },
    { l: "\\rVert", n: "norma (fecha)", c: "∥" },
    { l: "\\langle", n: "ângulo esquerdo", c: "⟨", s: "\\lang" },
    { l: "\\lbrace", n: "chave esquerda", c: "{" },
    { l: "\\lbrack", n: "colchete esquerdo", c: "[" },
    { l: "\\lfloor", n: "piso esquerdo", c: "⌊" },
    { l: "\\lgroup", n: "grupo esquerdo", c: "⟮" },
    { l: "\\lparen", n: "parêntese esquerdo", c: "(" },
    { l: "\\rangle", n: "ângulo direito", c: "⟩", s: "\\rang" },
    { l: "\\rbrace", n: "chave direita", c: "}" },
    { l: "\\rbrack", n: "colchete direito", c: "]" },
    { l: "\\rfloor", n: "piso direito", c: "⌋" },
    { l: "\\rgroup", n: "grupo direito", c: "⟯" },
    { l: "\\rparen", n: "parêntese direito", c: ")" },
    { l: "\\backslash", n: "barra invertida", c: "\\" },
    { l: "\\lmoustache", n: "bigode esquerdo", c: "⎰" },
    { l: "\\rmoustache", n: "bigode direito", c: "⎱" },
    { l: "\\lBrace", n: "chave dupla esquerda", c: "⦃" },
    { l: "\\rBrace", n: "chave dupla direita", c: "⦄" },
    { l: "\\llcorner", n: "canto inferior esquerdo", c: "⌞" },
    { l: "\\lrcorner", n: "canto inferior direito", c: "⌟" },
    { l: "\\ulcorner", n: "canto superior esquerdo", c: "⌜" },
    { l: "\\urcorner", n: "canto superior direito", c: "⌝" },
    { l: "\\llbracket", n: "colchete duplo esquerdo", c: "⟦" },
    { l: "\\mathstrut", n: "escora invisível (altura de parêntese)", c: "(" },
    { l: "\\rrbracket", n: "colchete duplo direito", c: "⟧" },
  ],
  acentos: [
    { l: "\\bar{@}", n: "barra em cima", m: "\\bar{x}" },
    { l: "\\dot{@}", n: "ponto em cima (derivada no tempo)", m: "\\dot{x}" },
    { l: "\\hat{@}", n: "chapéu", m: "\\hat{x}" },
    { l: "\\vec{@}", n: "vetor", m: "\\vec{v}" },
    { l: "\\angl{@}", n: "ângulo em volta", m: "\\angl{x}" },
    { l: "\\ddot{@}", n: "dois pontos em cima", m: "\\ddot{x}" },
    { l: "\\sout{@}", n: "riscado na horizontal", m: "\\sout{xy}" },
    { l: "\\acute{@}", n: "acento agudo", m: "\\acute{x}" },
    { l: "\\boxed{@}", n: "dentro de uma caixa", m: "\\boxed{x}" },
    { l: "\\breve{@}", n: "breve", m: "\\breve{x}" },
    { l: "\\check{@}", n: "chapéu invertido", m: "\\check{x}" },
    { l: "\\dddot{@}", n: "três pontos em cima", m: "\\dddot{x}" },
    { l: "\\grave{@}", n: "acento grave", m: "\\grave{x}" },
    { l: "\\phase{@}", n: "fase (ângulo)", m: "\\phase{x}" },
    { l: "\\tilde{@}", n: "til", m: "\\tilde{x}" },
    { l: "\\cancel{@}", n: "cortado (risco)", m: "\\cancel{xy}" },
    { l: "\\ddddot{@}", n: "quatro pontos em cima", m: "\\ddddot{x}" },
    { l: "\\utilde{@}", n: "til embaixo", m: "\\utilde{x}" },
    { l: "\\bcancel{@}", n: "cortado ao contrário", m: "\\bcancel{xy}" },
    { l: "\\widehat{@}", n: "chapéu largo", m: "\\widehat{xy}" },
    { l: "\\xcancel{@}", n: "cortado em X", m: "\\xcancel{xy}" },
    { l: "\\mathring{@}", n: "anel em cima", m: "\\mathring{x}" },
    { l: "\\overline{@}", n: "barra em cima (larga)", m: "\\overline{xy}" },
    { l: "\\overgroup{@}", n: "arco em cima", m: "\\overgroup{ab}" },
    { l: "\\underline{@}", n: "barra embaixo", m: "\\underline{xy}" },
    { l: "\\widecheck{@}", n: "chapéu invertido largo", m: "\\widecheck{xy}" },
    { l: "\\widetilde{@}", n: "til largo", m: "\\widetilde{xy}" },
    { l: "\\undergroup{@}", n: "arco embaixo", m: "\\undergroup{ab}" },
    { l: "\\overbracket{@}", n: "colchete em cima", m: "\\overbracket{ab}" },
    { l: "\\overbrace{@}^{}", n: "chave em cima", m: "\\overbrace{ab}" },
    { l: "\\underbracket{@}", n: "colchete embaixo", m: "\\underbracket{ab}" },
    { l: "\\overleftarrow{@}", n: "seta para a esquerda em cima", m: "\\overleftarrow{AB}" },
    { l: "\\underbrace{@}_{}", n: "chave embaixo", m: "\\underbrace{ab}" },
    { l: "\\overrightarrow{@}", n: "seta para a direita em cima (vetor)", m: "\\overrightarrow{AB}" },
    { l: "\\underleftarrow{@}", n: "seta para a esquerda embaixo", m: "\\underleftarrow{AB}" },
    { l: "\\overlinesegment{@}", n: "segmento em cima", m: "\\overlinesegment{ab}" },
    { l: "\\underrightarrow{@}", n: "seta para a direita embaixo", m: "\\underrightarrow{AB}" },
    { l: "\\underlinesegment{@}", n: "segmento embaixo", m: "\\underlinesegment{ab}" },
    { l: "\\overleftrightarrow{@}", n: "seta dupla em cima", m: "\\overleftrightarrow{AB}" },
    { l: "\\underleftrightarrow{@}", n: "seta dupla embaixo", m: "\\underleftrightarrow{AB}" },
  ],
  estruturas: [
    { l: "\\sqrt{@}", n: "raiz quadrada", m: "\\sqrt{x}" },
    { l: "\\text{@}", n: "texto normal dentro da fórmula", m: "\\text{texto}" },
    { l: "\\smash{@}", n: "ignorar a altura", m: "\\smash{x}" },
    { l: "\\frac{@}{}", n: "fração", m: "\\frac{a}{b}" },
    { l: "\\textbf{@}", n: "texto em negrito", m: "\\textbf{texto}" },
    { l: "\\textit{@}", n: "texto em itálico", m: "\\textit{texto}" },
    { l: "\\binom{@}{}", n: "combinação (binomial)", m: "\\binom{n}{k}" },
    { l: "\\cfrac{@}{}", n: "fração continuada", m: "\\cfrac{a}{b}" },
    { l: "\\dfrac{@}{}", n: "fração grande", m: "\\dfrac{a}{b}" },
    { l: "\\phantom{@}", n: "espaço do tamanho de (invisível)", m: "\\phantom{x}" },
    { l: "\\tfrac{@}{}", n: "fração pequena", m: "\\tfrac{a}{b}" },
    { l: "\\xmapsto{@}", n: "leva a, com texto", m: "\\xmapsto{f}" },
    { l: "\\dbinom{@}{}", n: "combinação grande", m: "\\dbinom{n}{k}" },
    { l: "\\tbinom{@}{}", n: "combinação pequena", m: "\\tbinom{n}{k}" },
    { l: "\\vphantom{@}", n: "altura de (invisível)", m: "\\vphantom{x}" },
    { l: "\\overset{@}{}", n: "sobrepor em cima", m: "\\overset{a}{b}" },
    { l: "\\left(@\\right)", n: "parênteses que crescem", m: "\\left(x\\right)" },
    { l: "\\left[@\\right]", n: "colchetes que crescem", m: "\\left[x\\right]" },
    { l: "\\left|@\\right|", n: "módulo que cresce", m: "\\left|x\\right|" },
    { l: "\\stackrel{@}{}", n: "texto sobre a relação", m: "\\stackrel{a}{=}" },
    { l: "\\underset{@}{}", n: "sobrepor embaixo", m: "\\underset{a}{b}" },
    { l: "\\xleftarrow{@}", n: "seta para a esquerda com texto", m: "\\xleftarrow{f}" },
    { l: "\\xLeftarrow{@}", n: "seta dupla para a esquerda com texto", m: "\\xLeftarrow{f}" },
    { l: "\\xlongequal{@}", n: "igual longo com texto", m: "\\xlongequal{f}" },
    { l: "\\xrightarrow{@}", n: "seta para a direita com texto", m: "\\xrightarrow{f}" },
    { l: "\\xRightarrow{@}", n: "seta dupla para a direita com texto", m: "\\xRightarrow{f}" },
    { l: "\\left\\{@\\right\\}", n: "chaves que crescem", m: "\\left\\{x\\right\\}" },
    { l: "\\left\\|@\\right\\|", n: "norma que cresce", m: "\\left\\|x\\right\\|" },
    { l: "\\substack{@ \\\\ }", n: "linhas empilhadas sob o operador", m: "\\substack{a \\\\ b}" },
    { l: "\\xleftrightarrow{@}", n: "seta de dois lados com texto", m: "\\xleftrightarrow{f}" },
    { l: "\\genfrac{}{}{}{}{@}{}", n: "fração com delimitador livre", m: "\\genfrac(){}{0}{a}{b}" },
    { l: "\\xrightleftharpoons{@}{}", n: "equilíbrio com texto", m: "\\xrightleftharpoons{a}{b}" },
    { l: "\\left\\lceil @\\right\\rceil", n: "teto que cresce", m: "\\left\\lceil x\\right\\rceil" },
    { l: "\\left\\langle @\\right\\rangle", n: "ângulos que crescem", m: "\\left\\langle x\\right\\rangle" },
    { l: "\\left\\lfloor @\\right\\rfloor", n: "piso que cresce", m: "\\left\\lfloor x\\right\\rfloor" },
    { l: "\\begin{cases} @ \\\\  \\end{cases}", n: "sistema de equações", m: "\\begin{cases} a \\\\ b \\end{cases}" },
    { l: "\\begin{matrix} @ &  \\\\  &  \\end{matrix}", n: "matriz sem delimitador", m: "\\begin{matrix} a & b \\\\ c & d \\end{matrix}" },
    { l: "\\begin{array}{cc} @ &  \\\\  &  \\end{array}", n: "tabela alinhada", m: "\\begin{array}{cc} a & b \\\\ c & d \\end{array}" },
    { l: "\\begin{bmatrix} @ &  \\\\  &  \\end{bmatrix}", n: "matriz com colchetes", m: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}" },
    { l: "\\begin{Bmatrix} @ &  \\\\  &  \\end{Bmatrix}", n: "matriz com chaves", m: "\\begin{Bmatrix} a & b \\\\ c & d \\end{Bmatrix}" },
    { l: "\\begin{pmatrix} @ &  \\\\  &  \\end{pmatrix}", n: "matriz com parênteses", m: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}" },
    { l: "\\begin{vmatrix} @ &  \\\\  &  \\end{vmatrix}", n: "determinante", m: "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}" },
    { l: "\\begin{Vmatrix} @ &  \\\\  &  \\end{Vmatrix}", n: "norma de matriz", m: "\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}" },
    { l: "\\begin{aligned} @ &=  \\\\  &=  \\end{aligned}", n: "equações alinhadas pelo igual", m: "\\begin{aligned} a &= b \\end{aligned}" },
  ],
  estilos: [
    { l: "\\bm{@}", n: "símbolo em negrito (bm)", m: "\\bm{v}" },
    { l: "\\pmb{@}", n: "negrito falso (pmb)", m: "\\pmb{\\mu}" },
    { l: "\\mathbb{@}", n: "vazado (conjuntos numéricos)", m: "\\mathbb{R}" },
    { l: "\\mathbf{@}", n: "negrito", m: "\\mathbf{v}" },
    { l: "\\mathit{@}", n: "itálico", m: "\\mathit{x}" },
    { l: "\\mathrm{@}", n: "romano (reto)", m: "\\mathrm{d}" },
    { l: "\\mathsf{@}", n: "sem serifa", m: "\\mathsf{A}" },
    { l: "\\mathtt{@}", n: "monoespaçado", m: "\\mathtt{A}" },
    { l: "\\mathcal{@}", n: "caligráfico", m: "\\mathcal{L}" },
    { l: "\\mathscr{@}", n: "manuscrito", m: "\\mathscr{L}" },
    { l: "\\mathfrak{@}", n: "gótico (fraktur)", m: "\\mathfrak{g}" },
    { l: "\\textstyle @", n: "tamanho de linha", m: "\\textstyle\\sum" },
    { l: "\\boldsymbol{@}", n: "símbolo em negrito", m: "\\boldsymbol{\\alpha}" },
    { l: "\\mathnormal{@}", n: "itálico matemático padrão", m: "\\mathnormal{x}" },
    { l: "\\scriptstyle @", n: "tamanho de índice", m: "\\scriptstyle x" },
    { l: "\\displaystyle @", n: "tamanho de bloco", m: "\\displaystyle\\sum" },
    { l: "\\scriptscriptstyle @", n: "tamanho de índice de índice", m: "\\scriptscriptstyle x" },
  ],
  funcoes: [
    { l: "\\lg(@)", n: "logaritmo base 10", m: "\\lg" },
    { l: "\\ln(@)", n: "logaritmo natural", m: "\\ln" },
    { l: "\\Pr(@)", n: "probabilidade", m: "\\Pr" },
    { l: "\\arg(@)", n: "argumento", m: "\\arg" },
    { l: "\\cos(@)", n: "cosseno", m: "\\cos" },
    { l: "\\cot(@)", n: "cotangente", m: "\\cot" },
    { l: "\\csc(@)", n: "cossecante", m: "\\csc" },
    { l: "\\deg(@)", n: "grau (de polinômio)", m: "\\deg" },
    { l: "\\det(@)", n: "determinante", m: "\\det" },
    { l: "\\dim(@)", n: "dimensão", m: "\\dim" },
    { l: "\\exp(@)", n: "exponencial", m: "\\exp" },
    { l: "\\gcd(@)", n: "máximo divisor comum", m: "\\gcd" },
    { l: "\\ker(@)", n: "núcleo", m: "\\ker" },
    { l: "\\log(@)", n: "logaritmo", m: "\\log" },
    { l: "\\sec(@)", n: "secante", m: "\\sec" },
    { l: "\\sin(@)", n: "seno", m: "\\sin" },
    { l: "\\tan(@)", n: "tangente", m: "\\tan" },
    { l: "\\cosh(@)", n: "cosseno hiperbólico", m: "\\cosh" },
    { l: "\\coth(@)", n: "cotangente hiperbólica", m: "\\coth" },
    { l: "\\inf_{@}", n: "ínfimo", m: "\\inf" },
    { l: "\\log_{@}", n: "logaritmo de base b", m: "\\log_b" },
    { l: "\\max_{@}", n: "máximo", m: "\\max" },
    { l: "\\min_{@}", n: "mínimo", m: "\\min" },
    { l: "\\sinh(@)", n: "seno hiperbólico", m: "\\sinh" },
    { l: "\\sup_{@}", n: "supremo", m: "\\sup" },
    { l: "\\tanh(@)", n: "tangente hiperbólica", m: "\\tanh" },
    { l: "@ \\pmod{}", n: "módulo (entre parênteses)", m: "a \\pmod b" },
    { l: "\\arccos(@)", n: "arco cosseno", m: "\\arccos" },
    { l: "\\arcsin(@)", n: "arco seno", m: "\\arcsin" },
    { l: "\\arctan(@)", n: "arco tangente", m: "\\arctan" },
    { l: "\\sqrt[@]{}", n: "raiz de índice n", m: "\\sqrt[n]{x}" },
    { l: "\\liminf_{@}", n: "limite inferior", m: "\\liminf" },
    { l: "\\limsup_{@}", n: "limite superior", m: "\\limsup" },
    { l: "\\lim_{@ \\to }", n: "limite", m: "\\lim" },
    { l: "\\operatorname{@}", n: "nome de função próprio", m: "\\operatorname{f}" },
    { l: "\\bmod", n: "resto da divisão" },
    { l: "\\plim", n: "limite em probabilidade" },
    { l: "\\argmax", n: "argumento do máximo" },
    { l: "\\argmin", n: "argumento do mínimo" },
    { l: "\\injlim", n: "limite injetivo" },
    { l: "\\projlim", n: "limite projetivo" },
    { l: "\\varinjlim", n: "limite direto" },
    { l: "\\varliminf", n: "limite inferior (variante)" },
    { l: "\\varlimsup", n: "limite superior (variante)" },
    { l: "\\varprojlim", n: "limite inverso" },
  ],
  espacos: [
    { l: "\\space", n: "espaço", c: " " },
    { l: "\\nobreakspace", n: "nobreakspace", c: " " },
    { l: "\\quad", n: "espaço de um quadrat" },
    { l: "\\qquad", n: "espaço de dois quadrats" },
    { l: "\\enskip", n: "espaço de meia quadrat", s: "\\enspace" },
    { l: "\\newline", n: "quebra de linha" },
    { l: "\\medspace", n: "espaço médio" },
    { l: "\\thinspace", n: "espaço fino" },
    { l: "\\thickspace", n: "espaço largo" },
    { l: "\\negmedspace", n: "espaço médio negativo", c: "⁣" },
    { l: "\\negthinspace", n: "espaço fino negativo", c: "⁣" },
    { l: "\\negthickspace", n: "espaço largo negativo", c: "⁣" },
  ],
}
